USE MASTER
GO

IF NOT EXISTS (
    SELECT [name]
    FROM sys.databases
    WHERE [name] = N'Husbandry'
)
CREATE DATABASE Husbandry
GO

USE Husbandry
GO


DROP TABLE IF EXISTS Reptiles;
DROP TABLE IF EXISTS [User];
DROP TABLE IF EXISTS UserReptile;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS UserItem;
DROP TABLE IF EXISTS Care;
DROP TABLE IF EXISTS ReptileItem;


CREATE TABLE Reptiles (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	[Name] VARCHAR(55) NOT NULL,
	Temperature VARCHAR(55) NOT NULL,
	Humidity VARCHAR(55) NOT NULL,
	Difficulty VARCHAR(55) NOT NULL,
	Price VARCHAR(55) NOT NULL,
	CareFrequency VARCHAR(55) NOT NULL,
	[Availability] VARCHAR(55) NOT NULL,
	Handleability VARCHAR(55) NOT NULL
);

CREATE TABLE [User] (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	Email VARCHAR(255) NOT NULL
);

CREATE TABLE Item (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	[Type] VARCHAR(255) NOT NULL,
	[Desc] VARCHAR(255) NOT NULL,
	Link VARCHAR(255) NOT NULL
);

CREATE TABLE Care (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	[Type] VARCHAR(255) NOT NULL,
	[Desc] VARCHAR(255) NOT NULL,
	ReptileId INTEGER NOT NULL
);

CREATE TABLE UserReptile (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	UserId INTEGER NOT NULL,
	ReptileId INTEGER NOT NULL,
	CONSTRAINT FK_Reptile_User FOREIGN KEY (UserId) REFERENCES [User](Id) ON DELETE CASCADE
);

CREATE TABLE UserItem (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	UserId INTEGER NOT NULL,
	ItemId INTEGER NOT NULL,
	Purchased BIT NOT NULL,
	CONSTRAINT FK_Item_User FOREIGN KEY (UserId) REFERENCES [User](Id) ON DELETE CASCADE
);

CREATE TABLE ReptileItem (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	ReptileId INTEGER NOT NULL,
	ItemId INTEGER NOT NULL
);
